### ISSUE TITLE
ToDo Tasks

### ISSUE THREAD

**Issue by amanchik3007** [DotNetNomads/UltraMafia#1]
### **High Priority Tasks**
1. Limit victims or dead people from chatting
2. Repeat notification about starting game 
3. Chat ID issue
4. Limit healing after every two game rounds for Doctor
5. Add stickers ASAP 
6. Add leave from game feature 

### **Further Improvements**

1. Mobile Application on WebView 
2. Adding Events for interaction with an audience

**Comment by binali-rustamov** [comment]
1. Build Docker image
2. Save all progress to MySQL
